import type { Session } from "./types";

/** Copied unchanged from design/mockup-b.html */
export const MOCK_SESSIONS: Session[] = [
  {
    app: "claude code",
    model: "fable-5",
    title: "refactor auth middleware to session tokens",
    sent: "use the existing redis client, don’t add ioredis",
    state: "working",
    ctl: "tmux",
    tool: "Edit",
    toolArg: "src/auth/middleware.ts · +41 −18",
    think: [
      "the session token needs the same ttl as the redis key or refresh drifts",
      "checking whether verifySession is called anywhere outside middleware",
      "logout clears the cookie but not the redis entry — fixing that too",
    ],
    thinkIdx: 0,
    repo: "gx",
    br: "feature/auth-tokens",
    subs: [
      {
        target: "opencode",
        model: "gpt-5",
        state: "working",
        task: "integration tests for the new session flow",
      },
      {
        target: "codex",
        model: "o4-mini",
        state: "done",
        task: "update api docs for the token endpoints",
      },
    ],
  },
  {
    app: "codex",
    model: "gpt-5-codex",
    title: "fix flaky retry test in ci",
    sent: "failure is only on ubuntu-latest, so it’s timing — check the retry window",
    state: "done",
    age: "2m",
    ctl: "native",
    result: "✓ widened retry window to 250ms + jitter · 3 consecutive green runs",
    output: [
      "widened the window in test/retry.spec.ts:41",
      "jitter 0–80ms keeps p99 well under budget",
      "ran the suite 3× on ubuntu-latest — all green",
    ],
    subs: [],
  },
  {
    app: "claude.ai",
    model: "fable-5",
    title: "q3 roadmap narrative draft",
    sent: "tighten the security section, cut it by a third",
    state: "done",
    age: "11m",
    ctl: "observe",
    result: "✓ redraft ready — security section down from 900 to 580 words",
    output: [
      "cut the threat-model subsection, folded the key points into the overview",
      "kept the soc2 timeline — it anchors the whole quarter",
    ],
    subs: [],
    noAdopt: true,
  },
  {
    app: "cursor",
    model: "sonnet-5",
    title: "migrate dashboard to tailwind v4",
    sent: "keep the class sorting plugin, drop everything else from postcss",
    state: "working",
    ctl: "watch",
    tool: "Grep",
    toolArg: '"@apply" — 41 matches in 17 files',
    think: [
      "v4 drops @apply in css modules — these need inlining",
      "the dashboard grid arbitrary values map cleanly to v4 tokens",
      "postcss config is legacy, replacing with @tailwindcss/vite",
    ],
    thinkIdx: 0,
    repo: "dashboard",
    br: "tailwind-v4",
    subs: [],
  },
  {
    app: "opencode",
    model: "gpt-5",
    title: "integration tests for billing webhooks",
    sent: "cover the dunning and proration paths too",
    state: "input",
    ctl: "native",
    approval: "Bash(stripe fixtures pull --api-version 2026-03 --write test/fixtures/)",
    ask: "",
    subs: [],
  },
  {
    app: "claude code",
    model: "opus-4.8",
    title: "chase down memory leak in worker pool",
    sent: "bisect the heap growth, start from the queue consumer",
    state: "error",
    ctl: "tmux",
    fail: "✗ session stalled · no output for 12m · ⏎ to nudge",
    repo: "gx",
    br: "fix/worker-leak",
    wt: "wt-2",
    subs: [],
  },
  {
    app: "codex",
    model: "gpt-5",
    title: "audit npm scripts for postinstall hooks",
    sent: "flag anything that runs code on install, dev deps included",
    state: "done",
    age: "24m",
    ctl: "native",
    result: "✓ 2 packages flagged — esbuild pinned, husky postinstall removed",
    output: [
      "esbuild: pinned to 0.27.4, checksum verified",
      "husky: replaced postinstall with a prepare script",
    ],
    subs: [],
  },
  {
    app: "claude.ai",
    model: "fable-5",
    title: "competitor pricing teardown",
    sent: "focus on the enterprise tiers, ignore the free plans",
    state: "working",
    ctl: "observe",
    noAdopt: true,
    tool: "WebSearch",
    toolArg: '"acme enterprise tier pricing 2026"',
    think: [
      "their enterprise page hides seat minimums — checking the sales pdf",
      "usage-based add-ons make the sticker price misleading",
      "building the comparison around effective per-seat cost",
    ],
    thinkIdx: 0,
    subs: [],
  },
  {
    app: "claude code",
    model: "opus-4.8",
    title: "tune retry backoff in gx cloud sync",
    sent: "cap the backoff at 30s and add jitter",
    state: "done",
    age: "18m",
    ctl: "observe",
    sid: "8f3a21c9",
    result: "✓ backoff capped at 30s + full jitter — sync tests green",
    output: [
      "exponential base stays 500ms, cap 30s",
      "jitter is full-range to avoid thundering herd",
    ],
    repo: "gx",
    br: "feature/sync-backoff",
    subs: [],
  },
];

export const HISTORY = [
  {
    when: "today 09:12",
    title: "wire stripe webhook retries",
    app: "claude code",
    model: "fable-5",
    num: "212K · $0.61",
    note: "merged pr #91",
  },
  {
    when: "today 08:40",
    title: "bump vite to 7.1",
    app: "codex",
    model: "gpt-5-codex",
    num: "48K · sub",
    note: "landed on main",
  },
  {
    when: "yesterday",
    title: "fix oauth callback loop",
    app: "cursor",
    model: "sonnet-5",
    num: "156K · sub",
    note: "shipped in 0.9.3",
  },
  {
    when: "jul 05",
    title: "benchmark warm-start latency",
    app: "opencode",
    model: "glm-5.2",
    num: "301K · $0.22",
    note: "report in scratch/bench.md",
  },
  {
    when: "jul 04",
    title: "rewrite queue consumer in go",
    app: "claude code",
    model: "opus-4.8",
    num: "1.1M · $2.84",
    note: "abandoned — kept node impl",
  },
  {
    when: "jul 03",
    title: "add rate limiting to public api",
    app: "codex",
    model: "gpt-5",
    num: "410K · $0.74",
    note: "merged pr #83",
  },
];

export const TARGETS = [
  { id: "opencode", label: "opencode", desc: "local cli · any provider" },
  { id: "codex", label: "codex", desc: "openai · terminal" },
  { id: "claude", label: "claude code", desc: "anthropic · terminal" },
  { id: "cursor", label: "cursor agent", desc: "ide background agent" },
];

export const MODELS: Record<string, string[]> = {
  opencode: ["claude-sonnet-5", "gpt-5", "glm-5.2", "qwen3-coder"],
  codex: ["gpt-5-codex", "gpt-5", "o4-mini"],
  claude: [
    "claude-fable-5",
    "claude-opus-4-8",
    "claude-sonnet-5",
    "claude-haiku-4.5",
  ],
  cursor: ["composer-2", "claude-sonnet-5", "gpt-5"],
};

export const ROOT_CMDS = [
  {
    id: "subagents",
    label: "/subagents",
    desc: "hand this session’s work to another app + model",
  },
  {
    id: "plan",
    label: "/plan",
    desc: "draft a plan first — executes only after you approve",
  },
  {
    id: "review",
    label: "/review",
    desc: "spawn a reviewer on this session’s diff",
  },
  {
    id: "loop",
    label: "/loop",
    desc: "keep re-running until you stop it",
  },
  {
    id: "broadcast",
    label: "/broadcast",
    desc: "send the prompt to every live session",
  },
  {
    id: "handoff",
    label: "/handoff",
    desc: "move this session — context and all — to another harness",
  },
  {
    id: "new",
    label: "/new",
    desc: "start a fresh session — pick harness + model",
  },
  {
    id: "worktree",
    label: "/worktree",
    desc: "move this session into a fresh git worktree",
  },
  {
    id: "compact",
    label: "/compact",
    desc: "compact this session’s context window",
  },
  {
    id: "kill",
    label: "/kill",
    desc: "end this session",
  },
];

export const PAL = [
  { id: "session", label: "session", desc: "back to the selected session" },
  {
    id: "history",
    label: "history",
    desc: "finished sessions — searchable, stored locally",
  },
  { id: "usage", label: "usage", desc: "tokens & cost by model" },
  { id: "access", label: "access", desc: "keys & subscriptions" },
  {
    id: "settings",
    label: "settings",
    desc: "notifications · sources · general",
  },
  {
    id: "subagents",
    label: "/subagents",
    desc: "hand off from the selected session",
  },
  {
    id: "broadcast",
    label: "/broadcast",
    desc: "prompt every live session",
  },
];
